Make this package easier to run
TukuToi/CP-Coding-Standards pull request #1
Opened 2021-11-23 19:12 UTC by nylen

This PR updates the readme to add full installation and usage instructions at the top of the readme. It adds a `bin/cpcs` script which is both an easier way to run this ruleset and a next step towards automating this process for plugins. This PR also makes a couple of changes to the `phpcs.xml` rules:

- Disable the `Squiz.PHP.EmbeddedPhp.ContentBeforeEnd` formatting rule which showed up for me while I was playing with this project.
- Respect `phpcs:ignore` annotations, and document in the readme how to show all warnings/errors including those that are ignored. Specific `phpcs:ignore` comments accompanied by explanations of why a given rule is being ignored should be accepted as a way to pass the coding standards checks.

It's better to specify options _at runtime_ rather than requiring users to edit the `phpcs.xml` directly. For the `text_domain` setting, this can be done via `--runtime-set text_domain plugin-textdomain`: https://github.com/WordPress/WordPress-Coding-Standards/blob/7da1894633f168fe244afc6de00d141f27517b62/WordPress/Sniffs/WP/I18nSniff.php#L193-L197

The `minimum_supported_wp_version` setting should have similar treatment, but I think this should be saved for a separate PR: https://github.com/WordPress/WordPress-Coding-Standards/blob/dc2f21771cb2b5336a7e6bb6616abcdfa691d7de/WordPress/Helpers/MinimumWPVersionTrait.php#L60

2021-11-23 23:12 UTC, nylen commented on bin/cpcs
> +	echo "(or use . for current directory)"
```suggestion
	echo "(to check the current directory, use . for plugin-directory-name)"
```

2021-11-25 09:10 UTC, TukuToi requested changes
This all looks good to me, the only I want to follow persistently is the order of rules in the file, so this 
```
<exclude name="Squiz.PHP.DisallowMultipleAssignments.FoundInControlStructure"/>
<exclude name="Squiz.PHP.CommentedOutCode.Found"/>
<exclude name="Squiz.Strings.ConcatenationSpacing.PaddingFound"/>
<exclude name="Squiz.PHP.EmbeddedPhp.ContentBeforeEnd"/>
```

Would have to become this
```
<exclude name="Squiz.PHP.CommentedOutCode.Found"/>
<exclude name="Squiz.PHP.DisallowMultipleAssignments.FoundInControlStructure"/>
<exclude name="Squiz.PHP.EmbeddedPhp.ContentBeforeEnd"/>
<exclude name="Squiz.Strings.ConcatenationSpacing.PaddingFound"/>
```

(I am aware that the current file probably still has some non-alphabetically ordered rules, but the intention is that we'd order the rules alphabetically by first letter, for each ruleset, starting at the first word and then second, third, etc)
It stays more structured and easy to find things

2021-11-27 01:37 UTC, nylen commented
Ok, no problem. I fixed the rule order in the whole file. It would be a good idea to set up a GitHub Actions job so that it stays that way, but that is out of scope for this PR.

I also fixed a bunch of whitespace issues (indentation with a mix of tabs and spaces, spaces after the end of lines). I am all for keeping spacing consistent in my own code, but we can't enforce this kind of thing on everyone as it is a purely cosmetic issue.

2021-11-27 02:53 UTC, TukuToi approved these changes

2021-11-27 02:54 UTC, merged